# Generated by Django 2.1.5 on 2020-06-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_remove_products_added_by_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_old_price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
    ]
