# Generated by Django 2.1.5 on 2020-06-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_products_product_old_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_desc',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(max_length=200),
        ),
    ]
