# Generated by Django 2.1.5 on 2020-06-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_auto_20200613_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='houseno',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
